const currentScript=document.currentScript;
const assetBase=new URL('assets/',currentScript.src).href;
const brandAssetBase=new URL('assets/Brand/',currentScript.src).href;
const header=document.querySelector('.site-header');
if(header){const brand=header.querySelector('.brand');const logoFile=header.classList.contains('on-light')?'node8%20logo_black.png':'node8%20logo_white.png';if(brand){brand.setAttribute('aria-label','Node8 Studio home');brand.replaceChildren(Object.assign(document.createElement('img'),{src:`${brandAssetBase}${logoFile}`,alt:'Node8 Studio'}))}}
if(!document.querySelector('link[rel~="icon"]')){const favicon=document.createElement('link');favicon.rel='icon';favicon.type='image/png';favicon.href=`${brandAssetBase}%ED%8C%8C%EB%B9%84%EC%BD%984.png`;document.head.appendChild(favicon)}
if(new URLSearchParams(location.search).get('tune')==='1'){document.querySelectorAll('a[href]').forEach(link=>{const destination=new URL(link.getAttribute('href'),location.href);if(destination.origin===location.origin&&!link.hasAttribute('download')){destination.searchParams.set('tune','1');link.href=destination.href}})}
const publicTune=document.createElement('script');publicTune.src=new URL('public-tune.js?v=20260930',currentScript.src).href;document.head.appendChild(publicTune);
if(new URLSearchParams(location.search).get('tune')==='1'){publicTune.onload=()=>{const tuneText=document.createElement('script');tuneText.src=new URL('tune-text.js',currentScript.src).href;tuneText.onload=()=>{const tuneScript=document.createElement('script');tuneScript.src=new URL('tune.js?v=home-intro-mobile-lines-v2-20260924',currentScript.src).href;document.head.appendChild(tuneScript)};document.head.appendChild(tuneText)}}
const carouselScript=document.createElement('script');carouselScript.src=new URL('recent-carousel.js?v=mobile-recent-swipe-autoplay-v3-20260924',currentScript.src).href;carouselScript.defer=true;document.head.appendChild(carouselScript);
if(!document.querySelector('script[data-node8-cms]')){const cmsScript=document.createElement('script');cmsScript.src=new URL('cms-public.js?v=early-hero-20260929',currentScript.src).href;cmsScript.defer=true;document.head.appendChild(cmsScript);}

const oldContact=document.querySelector('.contact');
const oldFooter=document.querySelector('footer');
if(oldContact&&oldFooter){
  const footer=document.createElement('footer');
  footer.className='node8-footer';footer.id='contact';
  footer.innerHTML=`<div class="node8-footer-shell"><section class="node8-footer-contact"><h2 class="node8-footer-title">Let's Create Moments</h2><div class="node8-footer-content"><p class="node8-footer-copy">아직 한 줄뿐인 아이디어여도 괜찮습니다.<br>카카오톡이나 메일로 편하게 들려주세요.<br>자료를 함께 보내주시면 더 깊이 이야기 나눌 수 있습니다.</p><a class="node8-footer-button" href="http://pf.kakao.com/_LfWan/chat" target="_blank" rel="noopener noreferrer">카톡 상담</a><p class="node8-footer-email">studio@node8.kr</p><div class="node8-footer-socials"><a href="https://www.instagram.com/node8_studio" target="_blank" rel="noopener noreferrer">Instagram</a><a href="https://www.youtube.com/@Node8_studio" target="_blank" rel="noopener noreferrer">Youtube</a><a href="https://www.threads.com/@node8_studio" target="_blank" rel="noopener noreferrer">Threads</a></div></div><div class="node8-footer-media" aria-label="Node8 contact reel"><video muted loop playsinline preload="auto" poster="${assetBase}footer-reel-poster.webp" aria-hidden="true"><source src="${assetBase}footer-reel-optimized.mp4" type="video/mp4"></video></div><img class="node8-footer-mark" src="https://framerusercontent.com/images/XGNkp1qzxs0swgY9DixdpCizO4.png?scale-down-to=512&width=916&height=106" alt=""></section><section class="node8-footer-info"><p class="node8-footer-address">서울 성동구 성수일로12길 17, 2층 Node8 Studio</p><p class="node8-footer-legal">150컴퍼니&nbsp;&nbsp;|&nbsp;&nbsp;대표자 황문석&nbsp;&nbsp;|&nbsp;&nbsp;882-63-00504</p><p class="node8-footer-legal">studio@node8.kr</p><p class="node8-footer-legal copyright">© Node8 All rights reserved</p><p class="node8-footer-tagline">We blend AI and human sensibility<br>to craft distinctive visuals for brands</p></section></div>`;
  const footerContent=footer.querySelector('.node8-footer-content');const footerMedia=footer.querySelector('.node8-footer-media');const footerBody=document.createElement('div');footerBody.className='node8-footer-body';footerContent.before(footerBody);footerBody.append(footerContent,footerMedia);
  const footerVideo=footerMedia.querySelector('video');if(footerVideo){footerVideo.style.cssText='display:block;width:100%;height:100%;object-fit:cover';footerVideo.muted=true;if('IntersectionObserver' in window){const playObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)footerVideo.play().catch(()=>{});else footerVideo.pause()}));playObserver.observe(footerVideo)}else footerVideo.play().catch(()=>{})}

  oldContact.replaceWith(footer);oldFooter.remove();
}

document.querySelector('.node8-footer-mark')?.setAttribute('src',`${brandAssetBase}node8%20logo_white.png`);
const button=document.querySelector('.top-button');
const menuButton=document.querySelector('.menu-button');
const nav=document.querySelector('.nav');
const menuStyles=document.createElement('style');
menuStyles.textContent='@media(max-width:720px){.nav.is-open{position:absolute;top:64px;right:20px;display:flex;flex-direction:column;align-items:flex-start;gap:16px;min-width:156px;padding:18px 20px;border-radius:14px;background:rgba(18,18,18,.86);color:#fff;backdrop-filter:blur(14px)}.site-header.on-light .nav.is-open{background:rgba(255,255,255,.9);color:#131313}}';
document.head.appendChild(menuStyles);
addEventListener('scroll',()=>button?.classList.toggle('is-visible',scrollY>440),{passive:true});
button?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
menuButton?.addEventListener('click',()=>{const open=nav.classList.toggle('is-open');menuButton.setAttribute('aria-expanded',String(open))});
document.querySelectorAll('.detail-film-trigger[data-youtube-id]').forEach((trigger)=>{trigger.addEventListener('click',()=>{const frame=trigger.closest('.detail-film-frame');const videoId=trigger.dataset.youtubeId;if(!frame||!videoId)return;const player=document.createElement('iframe');player.className='detail-film-embed';player.src=`https://www.youtube-nocookie.com/embed/${encodeURIComponent(videoId)}?autoplay=1&rel=0&modestbranding=1`;player.title=trigger.getAttribute('aria-label')||'Project film';player.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';player.allowFullscreen=true;frame.replaceChildren(player)})});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-shown');observer.unobserve(entry.target)}}),{threshold:.14});
document.querySelectorAll('.reveal').forEach(element=>observer.observe(element));
const aboutDiptych=document.querySelector('.about-diptych');
if(aboutDiptych&&!matchMedia('(prefers-reduced-motion: reduce)').matches){
  const panels=[...aboutDiptych.querySelectorAll('.about-diptych-panel')];
  let diptychFrame;
  const updateDiptych=()=>{diptychFrame=undefined;const bounds=aboutDiptych.getBoundingClientRect();const distance=Math.max(-1,Math.min(1,(innerHeight*.5-(bounds.top+bounds.height*.5))/innerHeight));const drift=parseFloat(getComputedStyle(aboutDiptych).getPropertyValue('--about-diptych-drift'))||8;panels.forEach((panel,index)=>panel.style.setProperty('--diptych-drift',`${Math.round(distance*(index?drift:-drift))}px`))};
  const requestDiptych=()=>{if(!diptychFrame)diptychFrame=requestAnimationFrame(updateDiptych)};
  addEventListener('scroll',requestDiptych,{passive:true});addEventListener('resize',requestDiptych);requestDiptych();
}
const recentRail=null;
if(recentRail){const originals=[...recentRail.querySelectorAll('.recent-card')];const firstClone=originals[0].cloneNode(true),lastClone=originals.at(-1).cloneNode(true);firstClone.setAttribute('aria-hidden','true');lastClone.setAttribute('aria-hidden','true');recentRail.prepend(lastClone);recentRail.append(firstClone);const cardStep=()=>recentRail.querySelector('.recent-card')?.getBoundingClientRect().width+16||0;requestAnimationFrame(()=>{recentRail.scrollLeft=cardStep()});const step=direction=>recentRail.scrollBy({left:direction*cardStep(),behavior:'smooth'});document.querySelector('.recent-prev')?.addEventListener('click',()=>step(-1));document.querySelector('.recent-next')?.addEventListener('click',()=>step(1));let startX=0,startScroll=0,dragging=false,resetTimer;recentRail.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'){startX=event.clientX;startScroll=recentRail.scrollLeft;dragging=true;recentRail.setPointerCapture(event.pointerId)}});recentRail.addEventListener('pointermove',event=>{if(dragging){recentRail.scrollLeft=startScroll-(event.clientX-startX)}});recentRail.addEventListener('pointerup',event=>{if(dragging){dragging=false;recentRail.releasePointerCapture(event.pointerId)}});recentRail.addEventListener('wheel',event=>{if(event.shiftKey&&Math.abs(event.deltaY)>Math.abs(event.deltaX)){event.preventDefault();recentRail.scrollBy({left:event.deltaY,behavior:'smooth'})}},{passive:false});recentRail.addEventListener('scroll',()=>{clearTimeout(resetTimer);resetTimer=setTimeout(()=>{const unit=cardStep(),lastStart=unit*originals.length;if(recentRail.scrollLeft<unit*.35){recentRail.scrollTo({left:lastStart,behavior:'auto'})}else if(recentRail.scrollLeft>unit*(originals.length+.65)){recentRail.scrollTo({left:unit,behavior:'auto'})}},90)})}
addEventListener('load',()=>{const rail=document.querySelector('.recent-rail');const card=rail?.querySelector('.recent-card');if(rail&&card){requestAnimationFrame(()=>{const width=card.getBoundingClientRect().width;rail.scrollLeft=width+16-(rail.clientWidth-width)/2})}},{once:true});
if(recentRail){const controls=document.querySelector('.recent-controls');if(controls){recentRail.append(controls)}recentRail.addEventListener('dragstart',event=>event.preventDefault());recentRail.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'){event.preventDefault()}})}
if(recentRail){const controls=recentRail.querySelector('.recent-controls');if(controls){const viewport=document.createElement('div');viewport.className='recent-viewport';recentRail.before(viewport);viewport.append(recentRail,controls)}}
if(recentRail){let dragOriginX=0,dragOriginScroll=0;recentRail.addEventListener('mousedown',event=>{if(event.button===0){dragOriginX=event.clientX;dragOriginScroll=recentRail.scrollLeft}});recentRail.addEventListener('mouseup',event=>{const delta=event.clientX-dragOriginX;if(Math.abs(delta)>42){const cardWidth=recentRail.querySelector('.recent-card')?.getBoundingClientRect().width||0;recentRail.scrollTo({left:dragOriginScroll+(delta<0?1:-1)*(cardWidth+16),behavior:'smooth'})}})}
if(recentRail){let activePointer=null,pointerStartX=0,pointerStartScroll=0;recentRail.addEventListener('pointerdown',event=>{if(event.target.closest('button'))return;activePointer=event.pointerId;pointerStartX=event.clientX;pointerStartScroll=recentRail.scrollLeft;recentRail.setPointerCapture(event.pointerId)});recentRail.addEventListener('pointermove',event=>{if(event.pointerId!==activePointer)return;const delta=event.clientX-pointerStartX;if(Math.abs(delta)>3){event.preventDefault();recentRail.scrollLeft=pointerStartScroll-delta}});recentRail.addEventListener('pointerup',event=>{if(event.pointerId!==activePointer)return;const delta=event.clientX-pointerStartX;const cardWidth=recentRail.querySelector('.recent-card')?.getBoundingClientRect().width||0;if(Math.abs(delta)>42){recentRail.scrollTo({left:pointerStartScroll+(delta<0?1:-1)*(cardWidth+16),behavior:'smooth'})}activePointer=null;recentRail.releasePointerCapture(event.pointerId)});recentRail.addEventListener('pointercancel',()=>{activePointer=null})}
